### ISSUE TITLE
i18 issue with new install

### ISSUE THREAD

**Issue by gamesbook** [ckan/ckanext-showcase#26]
On a newly installed CKAN (with a number of other plugins installed) this error occurs:
```
File "/usr/lib/ckan/default/src/ckan/ckan/lib/i18n.py", line 145, in handle_request
     if lang in plugin.i18n_locales():
File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/showcase/plugin.py", line 285, in i18n_locales
     d in os.listdir(directory)
OSError: [Errno 2] No such file or directory: '/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/showcase/i18n'
```
The pip install of showcase did not raise any errors; but there is certainly no 'i18n' file or directory.

**Comment by brew** [comment]
I've uploaded a new version to pypi (1.0.2) which includes the i18n directory in the manifest. Let me know if it's still not working.

**Comment by gamesbook** [comment]
I am not sure if this related... but when I try a `pip install --upgrade` or even `pip uninstall` I now get the same type of errors raised here - https://github.com/ckan/ckanext-pdfview/issues/17 
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'ckanext'
```
I tried to apply all the suggested changes and patches outlined in that issue (including the setup.py approach) to showcase, but without success.

**Comment by brew** [comment]
Thanks - can you open a new issue for this, so it doesn't get lost.

**Comment by gamesbook** [comment]
#27
