### ISSUE TITLE
pip uninstall or upgrade error

### ISSUE THREAD

**Issue by gamesbook** [ckan/ckanext-showcase#27]
When I try a `pip install --upgrade` or even `pip uninstall` I get the same type of errors as raised here - https://github.com/ckan/ckanext-pdfview/issues/17 
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'ckanext'
```
I tried to apply all the suggested changes and patches outlined in that issue (including the setup.py approach) to showcase, but without success.

**Comment by gamesbook** [comment]
I installed "from scratch" with a clean copy of CKAN and had no problems - so possibly it was the faulty uninstall that triggered this?

**Comment by AnestisSelmani** [comment]
Hello,
I have created a CKAN Instance and I have installed the ckanext-showcase module.
Although the installation didn't raise any errors and I was able to add a few showcases when some of my users that I set as showcase administrators started adding showcases the module has stopped working.
1. The page {portal.url/showcase} can't be viewed unless I am connected as system administrator. When a user or even a showcase user tries to enter the page get's an internal server error.
2. From that point on when I am trying to create a new system administrator from console I get the bellow message (This is why I am writing the comment to this issue)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'ckanext'

3. The server log is
[ckanext_default.error.log.txt](https://github.com/ckan/ckanext-showcase/files/737083/ckanext_default.error.log.txt)

Because I don't have the ability to install the CKAN again now is there any suggestement how I can fix this? 

Any help would be greatly appreciated

**Comment by torfsen** [comment]
This might be related to issues with the [namespace packages](http://stackoverflow.com/questions/1675734/how-do-i-create-a-namespace-package-in-python) that CKAN extensions are using. Please check if the following steps solve your problem:

1. Install CKAN in a new virtualenv.
2. When installing CKAN extensions, make sure that you
    * Use the latest version (older versions of some extensions did not declare their namespace packages correctly, see for example ckan/ckan#2893)
    * When installing CKAN extensions using `pip`, always use the "editable mode" (`--editable` or `-e`) due to a problem in `pip` (pypa/pip#3).

If this does not solve your problem then please try to find out which extension is causing the issue.
