### ISSUE TITLE
UnicodeEncodeError when migrating Related Items

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckanext-showcase#4]
Here's the traceback:

```
There was a problem creating the showcase_package_association for "InsideAirbnb.com": "Action 'ckanext_showcase_package_association_create' not found"
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-showcase/ckanext/showcase/commands/migrate.py", line 37, in command
    self.migrate()
  File "/usr/lib/ckan/default/src/ckanext-showcase/ckanext/showcase/commands/migrate.py", line 82, in migrate
    print('There was a problem migrating "{0}": {1}'.format(related['title'], e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 55: ordinal not in range(128)
```

**Comment by jqnatividad** [comment]
Upon further investigation, this was happening for all the debugging print messages since the data in the DB is encoded in UTF-8.
Overcame it in my local install by doing encode('ascii', 'ignore') for all the {0} variables.

**Comment by brew** [comment]
Thanks @jqnatividad! I fixed a couple of other issues with the migrate script while I was there.
