### ISSUE TITLE
Ckanext-showcase creates a keyError ckanext is paster commands

### ISSUE THREAD

**Issue by AnestisSelmani** [ckan/ckanext-showcase#48]
Hello,

(At first I would like to comment that the error is probably connected to issue #27.)
 
I have installed a CKAN Instance and I have installed the ckanext-showcase module.
Although the installation didn't raise any errors and I was able to add a few showcases when some of my users that I had set as showcase administrators started adding showcases the module has stopped working.
1. The page {portal.url/showcase} can't be viewed unless I am connected as system administrator. When a user or even a showcase user tries to enter the page get's an internal server error.
2. From that point on when I am trying to create a new system administrator from console with the paster command (http://docs.ckan.org/en/latest/maintaining/getting-started.html#create-admin-user) I get the bellow message 
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/ckan/default/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'ckanext'

3. The server log is
[ckanext_default.error.log.txt](https://github.com/ckan/ckanext-showcase/files/738384/ckanext_default.error.log.txt)

Because I don't have the ability to install the CKAN again right now, is there any suggestions on how I to fix this? 

Any help would be greatly appreciated

**Comment by AnestisSelmani** [comment]
After looking to my server error logs I found that the error wasn't caused by the plugin ckanext-showcase but from the module ckanext-datarequests. The first part of my problem was connected to a server error coming at a 401 Unauthorized exception not being handled at version 1.0.2 of the plugin. As soon as I upgraded to the latest version 1.0.3 the error was fixed.
